### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by joshwizzy** [SumeetMoray/Nearby-Shops-Shop-Owner-app#1]
error: cannot find symbol class DaggerNetComponent
error: package org.nearbyshops.shopkeeperapp.PickFromShopInventory.PendingPayments does not exist
error: cannot find symbol class PaymentsPendingFragmentPFS

**Comment by SumeetMoray** [comment]
Yes there were few errors  ... so I have updated the code ... it should work now ... 
Please make sure you have latest android studio which currently is version number 3.2.1 ...

**Comment by SumeetMoray** [comment]
Which OS are you running windows or linux ?
Are you compiling from command line or from android studio ?
Have you downloaded the new updated code ? If no then download the updated code and test again .

You need to compile from android studio because initially it will not work from command line. It doesnt have local.properties file. 

I downloaded the zip file from the repository and tested on ubuntu OS. Its compiling just fine.

**Comment by joshwizzy** [comment]
Sorry, was still compiling the old code.
The updated code compiles successfully
